steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - '--no-cache'
    - '-t'
    - 'gcr.io/${PROJECT_ID}/github.com/path-check/${_SERVICE}:$BRANCH_NAME-$SHORT_SHA'
    - .
    - '-f'
    - Dockerfile
  id: Build
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - 'gcr.io/${PROJECT_ID}/github.com/path-check/${_SERVICE}:$BRANCH_NAME-$SHORT_SHA'
  id: Push
#
# Deploys a Cloud Run service.
#

- id: 'Deploy to Cloud Run'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:293.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run deploy "${_SERVICE}-${BRANCH_NAME}" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "${_PLATFORM}" \
      --namespace "${_NAMESPACE}" \
      --port "${_PORT}" \
      --cluster "${_CLUSTER_NAME}" \
      --cluster-location "${_CLUSTER_LOCATION}" \
      --image "gcr.io/${PROJECT_ID}/github.com/path-check/${_SERVICE}:$BRANCH_NAME-$SHORT_SHA"
images:
  - 'gcr.io/${PROJECT_ID}/github.com/path-check/${_SERVICE}:$BRANCH_NAME-$SHORT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _SERVICE_NAME: safeplaces-backend-translate-dev
  _SERVICE: safeplaces-backend-translate-dev
  _REGION: us-central1
  _SECRET_NAME: 
  _PORT: 8080
  _PLATFORM: gke
  _CLUSTER_NAME: safeplaces
  _CLUSTER_LOCATION: us-central1
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - safeplaces-backend-translate-dev
